version: '2'
services:
    base:
        build: .
        volumes:
            - ./src/server:/var/src/track/server
            - ./src/client:/var/src/track/client

    web:
        extends:
            service: base
        links:
            - postgres:postgres

    alembic:
        extends:
            service: base
        working_dir: /var/src/track/server
        links:
            - postgres:postgres
        entrypoint: alembic
        command: current

    ionic:
        extends:
            service: base
        working_dir: /var/src/track/client
        entrypoint: ionic
        command: serve --nobrowser

    dbadmin:
        image: postgres:9
        links:
            - postgres:postgres
        environment:
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGUSER=postgres
            - PGPASSWORD=postgres
        command: psql

    postgres:
        image: postgres:9
