version: '2'
services:
    web:
        build: .
        volumes:
            - ./src/server:/var/src/track/server
            - ./src/client:/var/src/track/client
        links:
            - postgres:postgres

    postgres:
        image: postgres:9
